<a href="https://colab.research.google.com/github/matheusapostulo/diabetes-machine-learning/blob/main/Diabetes_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORT LIBS

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# DIABETES DATASET

## Data Exploration

In [2]:
diabetes_dataset = pd.read_csv('diabetes.csv')

In [4]:
diabetes_dataset
# The dataset features are already at the same scale

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [5]:
diabetes_dataset.describe

<bound method NDFrame.describe of         Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                0.0     1.0       1.0        1.0  40.0     1.0     0.0
1                0.0     0.0       0.0        0.0  25.0     1.0     0.0
2                0.0     1.0       1.0        1.0  28.0     0.0     0.0
3                0.0     1.0       0.0        1.0  27.0     0.0     0.0
4                0.0     1.0       1.0        1.0  24.0     0.0     0.0
...              ...     ...       ...        ...   ...     ...     ...
253675           0.0     1.0       1.0        1.0  45.0     0.0     0.0
253676           2.0     1.0       1.0        1.0  18.0     0.0     0.0
253677           0.0     0.0       0.0        1.0  28.0     0.0     0.0
253678           0.0     1.0       0.0        1.0  23.0     0.0     0.0
253679           2.0     1.0       1.0        1.0  25.0     0.0     0.0

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                        0.0           0.0     0.0  ...            1.0
1                        0.0           1.0     0.0  ...            0.0
2                        0.0           0.0     1.0  ...            1.0
3                        0.0           1.0     1.0  ...            1.0
4                        0.0           1.0     1.0  ...            1.0
...                      ...           ...     ...  ...            ...
253675                   0.0           0.0     1.0  ...            1.0
253676                   0.0           0.0     0.0  ...            1.0
253677                   0.0           1.0     1.0  ...            1.0
253678                   0.0           0.0     1.0  ...            1.0
253679                   1.0           1.0     1.0  ...            1.0

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
0               0.0      5.0      18.0      15.0       1.0  0.0   9.0
1               1.0      3.0       0.0       0.0       0.0  0.0   7.0
2               1.0      5.0      30.0      30.0       1.0  0.0   9.0
3               0.0      2.0       0.0       0.0       0.0  0.0  11.0
4               0.0      2.0       3.0       0.0       0.0  0.0  11.0
...             ...      ...       ...       ...       ...  ...   ...
253675          0.0      3.0       0.0       5.0       0.0  1.0   5.0
253676          0.0      4.0       0.0       0.0       1.0  0.0  11.0
253677          0.0      1.0       0.0       0.0       0.0  0.0   2.0
253678          0.0      3.0       0.0       0.0       0.0  1.0   7.0
253679          0.0      2.0       0.0       0.0       0.0  0.0   9.0

        Education  Income
0             4.0     3.0
1             6.0     1.0
2             4.0     8.0
3             3.0     6.0
4             5.0     4.0
...           ...     ...
253675        6.0     7.0
253676        2.0     4.0
253677        5.0     2.0
253678        5.0     1.0
253679        6.0     2.0

[253680 rows x 22 columns]>